### ISSUE TITLE
Pyrrha (Pandora Integration)

### ISSUE THREAD

**Issue by janstadt** [floris-b/lms_tts_notify#18]
```
notify:
  - platform: lms_tts_notify
    name: kitchen
    entity_id: tts.piper
    tts_service: tts.speak
    media_player: media_player.the_kitchen
    device_group: group.parents
    force_play: true
    alert_sound: Alert
    volume: 0.5
```
Playback starts back up which is great but if i enqueue a pandora station, it restarts the station completely and not just pause/play the current song. So if im in the middle of a jam and i get a notification, it starts playing a different song. Not a huge deal, but curious if that is something that can be mitigated.
