### ISSUE TITLE
Chime TTS use doesnt play chime audio

### ISSUE THREAD

**Issue by Edz2K23** [floris-b/lms_tts_notify#24]
Installed both chime_tts and lms_notify from HACS (0.3.16) if I use the alert playlist I can play a notification alarm as expected but it has a gap between this and the notification message. However if I use the chime_tts options I get the message delivered but no chime. If I use the chime_tts action directly it does work but, obviously, doesnt have the functionality of lms_tts norify.

Im guessing I've missed an integration step somewhere but cant seem to find examples of the chime_tts usage only the suggested field settings.

**Comment by bjornenvall** [comment]
it doesn't work in my setup either..

**Comment by Edz2K23** [comment]
Thanks for the confirmation Im not just doing something totally daft :)

**Comment by floris-b** [comment]
I did not make the Chime TTS option, afterwards when testing it myself I got mixed results with it and maybe I should not have integrated it

**Comment by louisc** [comment]
Not sure on the etiquette of commenting on a closed issue, but after spending a few hours on this, I have it working so thought id share a few discoveries. 

I found the example in the pull request to be useful for setup: https://github.com/floris-b/lms_tts_notify/pull/19

Audio was cutting out before being finished:
HA Settings > Integrations > ChimeTTS > Configure > Delay (in Milliseconds) before removing temporary files: 8000
(Set to 8s but that may be overkill)

Be sure to configure the rest of this properly. (https://nimroddolev.github.io/chime_tts/docs/documentation/configuration)

This is an example of a config for a player that finally got it working for me (I am using Home Assistant Cloud):
```yaml
notify:
  # Study
  - platform: lms_tts_notify
    name: StudyLMS
    tts_service: chime_tts.say
    entity_id: tts.home_assistant_cloud 
    media_player: media_player.study
    device_group: group.occupants
    force_play: true
    chimetts_chime_path: chord
    chimetts_offset: -500
    volume: 0.5
```

I found I had to restart HA to get these to take effect (reloading notify / all yaml was not enough)

I could then test call this successfully with:
```yaml
action: lms_tts_notify.queue
data:
  entity_id: media_player.study
  message: "The next train has been delayed. "
  chimetts_offset: -500
  chimetts_chime_path: chord
```
