### ISSUE TITLE
alert_sound overwrite

### ISSUE THREAD

**Issue by Skysurfer-14** [floris-b/lms_tts_notify#7]
I have defined 2 notifies with different alert sounds. The fist defined alarm sound is overwritten by the second. So both notifies use the alarm sound "Hinweis".

After deleting the the second notify "Sound_Aktor_Hinweis", the first notify is played with the right alert sound.

```
notify:
  - platform: lms_tts_notify
    name: Sound_Aktor_Alarm
    tts_service: tts.google_say
    media_player: media_player.squeezelite_997344
    device_group: group.all_persons
    alert_sound: Alarm
    volume: 1.0
  - platform: lms_tts_notify
    name: Sound_Aktor_Hinweis
    tts_service: tts.google_say
    media_player: media_player.squeezelite_997344
    device_group: group.all_persons
    alert_sound: Hinweis
    volume: 0.8
```
